### ISSUE TITLE
Setting Window Not Updating

### ISSUE THREAD

**Issue by TheLostCookie** [adlez27/akorin#5]
If the backend of the parameters in the SettingsWindow are updated (e.g. font-size is changed, NotesFile is changed), the UI does not immediately update to reflect the change and requires a refresh (e.g. closing and reopening the SettingsWindow).

**Comment by TheLostCookie** [comment]
Realized that these were two separate "issues."

The first is that browsing files/folders genuinely wasn't updating (fixed this with a "temporary" workaround).

The second is that the display tab currently only has font-size as an editable field, so once the field was in focus, there's currently no way to "unfocus" it yet and force an update. Thus, it is working as intended.

**Comment by adlez27** [comment]
This is the plan for how the settings window should work
1. While settings are being edited, they're continuously being validated
2. If all settings in all tabs are valid, the `OK` button and `Set as default` button are enabled. Otherwise, they're disabled. Closing the window using the X acts the same as `Cancel`.
3. If the current project file exists, OK will save the settings to the project file. If it doesn't exist yet, a file save browser opens to save the project file (using the specified destination folder as the default location). After saving, the settings window closes and settings are applied to the main window.
